trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

variables:
- group: AzureLiveTests

stages:
  - stage: azure_live_functional
    displayName: Custodian Live Functional Tests

    jobs:
    - job: 'azure_nightly_test_run'
      displayName: 'Azure Nightly Test Run'
      timeoutInMinutes: 0
      cancelTimeoutInMinutes: 0

      pool:
        vmImage: 'Ubuntu-18.04'

      steps:
        - checkout: self
          fetchDepth: 1

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
            architecture: 'x64'

        - script: python -m pip install --upgrade pip && pip install . && pip install -r requirements-dev.txt
          displayName: "Install Dependencies"

        - script: az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID} && az account set -s ${AZURE_SUBSCRIPTION_ID}
          displayName: "Login to Azure"
          env:
            AZURE_CLIENT_ID: $(azure-client-id)
            AZURE_CLIENT_SECRET: $(azure-client-secret)
            AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
            AZURE_TENANT_ID: $(azure-tenant-id)

        # Skip some resources due to some restrictions with their provisioning using Service Principal account
        # We maintain those resources in the test subscription available for the tests
        - script: /bin/bash tools/c7n_azure/tests_azure/templates/provision.sh --skip keyvault cost-management-export containerservice databricks postgresql
          displayName: "Provision Azure Resources"
          env:
            AZURE_CLIENT_ID: $(azure-client-id)
            AZURE_CLIENT_SECRET: $(azure-client-secret)

        - script: C7N_TEST_RUN=true C7N_FUNCTIONAL=yes pytest -v -m "not skiplive" tools/c7n_azure/tests_azure
          displayName: "Run Azure tests without cassettes"

        - script: /bin/bash tools/c7n_azure/tests_azure/templates/cleanup.sh --skip keyvault cost-management-export containerservice databricks postgresql
          displayName: "Cleanup Azure Resources"
          condition: always()

    - job: 'azure_nightly_functions_test'
      displayName: 'Azure Functions Nightly Test'
      timeoutInMinutes: 0
      cancelTimeoutInMinutes: 0

      pool:
        vmImage: 'Ubuntu-18.04'

      steps:
        - checkout: self
          fetchDepth: 1

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
            architecture: 'x64'

        - script: python -m pip install --upgrade pip && pip install . && pip install -r requirements-dev.txt
          displayName: "Install Dependencies"

        - script: /bin/bash test_functions.sh
          workingDirectory: tools/c7n_azure/tests_azure/azure-functions
          displayName: "Run Azure Functions Test"
          env:
            AZURE_CLIENT_ID: $(azure-client-id)
            AZURE_CLIENT_SECRET: $(azure-client-secret)
            AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
            AZURE_TENANT_ID: $(azure-tenant-id)

  # If all functional test stages complete successfully then
  # push a docker image and tag `nightly`.
  - stage: post_success
    displayName: After Successful Functional Tests
    dependsOn: azure_live_functional

    jobs:
      - job: 'push_docker_nightly'
        displayName: 'Push Nightly Docker Image'

        pool:
          vmImage: 'Ubuntu-18.04'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
              architecture: 'x64'

          - script: |
              python -m pip install --upgrade pip
              pip install click docker pytest pyyaml
            displayName: "Install Dependencies"

          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: dockerServiceConnection

          # cli
          - script: python tools/dev/dockerpkg.py build --test --push --tag nightly -r cloudcustodian -i cli
            displayName: build, test, push custodian cli nightlies

          # cli-org
          - script: python tools/dev/dockerpkg.py build --test --push --tag nightly -r cloudcustodian -i org
            displayName: build, test, push custodian org nightlies

          # mailer
          - script: python tools/dev/dockerpkg.py build --test --push --tag nightly -r cloudcustodian -i mailer
            displayName: build, test, push custodian mailer nightlies

          # mailer
          - script: python tools/dev/dockerpkg.py build --test --push --tag nightly -r cloudcustodian -i policystream
            displayName: build, test, push custodian policystream nightlies
